default:
  image: proxy.ai-lab.ir/docker:25.0
  services:
    - name: docker:dind
      command:
        - --tls=false
        - --registry-mirror=https://proxy.ai-lab.ir
        - --insecure-registry=proxy.ai-lab.ir
  before_script:
    - mkdir -p ~/.docker
    - |
      cat > ~/.docker/config.json <<EOF
      {
        "auths": {
          "proxy.ai-lab.ir": {
            "auth": "$(echo -n "devops:1qaz!QAZ" | base64)"
          }
        }
      }
      EOF

# variables:
#   DOCKER_TLS_CERTDIR: ""
  # DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - update

build-docker-image:
  stage: build
  script:
    - echo $CI_REGISTRY
    - docker build -t proxy.ai-lab.ir/platform/$CI_PROJECT_NAME:$CI_COMMIT_TAG .
    - echo "1qaz!QAZ" | docker login proxy.ai-lab.ir -u devops --password-stdin
    - docker image push proxy.ai-lab.ir/platform/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  only:
    - /^v[0-9]+(\.[0-9]+){0,2}(-rc\.[0-9]+)?$/


release-candidate-gitops:
  stage: update
  variables:
    GITOPS_CI_IMAGE_NAMESPACE: '$CI_PROJECT_NAMESPACE'
    GITOPS_CI_IMAGE_NAME: '$CI_PROJECT_NAME'
    GITOPS_CI_IMAGE_TAG: '$CI_COMMIT_TAG'
    GITOPS_CI_TRIGGER: 'true'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(?:\.[0-9]+)+-rc\.[0-9]+$/'
  trigger:
    project: platform/aip-gitops
    branch: main

production-gitops:
  stage: update
  variables:
    GITOPS_CI_IMAGE_NAMESPACE: '$CI_PROJECT_NAMESPACE'
    GITOPS_CI_IMAGE_NAME: '$CI_PROJECT_NAME'
    GITOPS_CI_IMAGE_TAG: '$CI_COMMIT_TAG'
    GITOPS_CI_TRIGGER: 'true'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+){0,2}$/'
  trigger:
    project: platform/aip-gitops
    branch: main
