default:
  image: proxy.ai-lab.ir/docker
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_IMAGE: $NEXUS_URL/kong/$CI_PROJECT_NAME:$CI_COMMIT_TAG



stages:
  - build
  - update-manifest



build-image:
  stage: build
  before_script:
    - echo "192.168.244.150 proxy.ai-lab.ir" >> /etc/hosts
    - docker login -u "$NEXUS_USERNAME" -p "$NEXUS_PASSWORD" $NEXUS_URL
  script:
    - echo "Building image:" "$DOCKER_IMAGE"
    - docker build -f Dockerfile.Deploy -t $DOCKER_IMAGE .
    - echo "Push image:"
    - docker push $DOCKER_IMAGE
  tags:
    - k8s-runner
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(?:\.[0-9]+)+-rc\.[0-9]/'

