default:
  image: proxy.ai-lab.ir/docker:25.0
  services:
    - name: docker:dind
      alias: docker
      command:
        - --tls=false
        - --registry-mirror=https://proxy.ai-lab.ir
        - --insecure-registry=proxy.ai-lab.ir
  before_script:
    - docker login -u "$NEXUS_USERNAME" -p "$NEXUS_PASSWORD" $NEXUS_URL
variables:
  DOCKER_IMAGE: $NEXUS_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG

stages:
  - test      # Add test stage
  - docs      # Documentation build
  - build     # Docker build
  - update    # GitOps update

# --- Testing Stage ---
test:
  stage: test
  image: python:3.13
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python tests/test_ci.py
  artifacts:
    expire_in: 1 week
  only:
    - main
    - merge_requests

# --- Sphinx Docs ---
docs-build:
  stage: docs
  image: python:3.13
  script:
    - pip install --upgrade pip
    - pip install -r docs/requirements.txt
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/_build/html
    expire_in: 1 week
  only:
    - main

pages:
  stage: docs
  image: python:3.13
  script:
    - pip install --upgrade pip
    - pip install -r docs/requirements.txt
    - cd docs
    - make html
    - mkdir -p ../public
    - cp -r _build/html/* ../public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main

# --- Docker Build Stage ---
build-image:
  stage: build
  image: proxy.ai-lab.ir/docker:25.0
  services:
    - name: docker:dind
      alias: docker
      command:
        - --tls=false
        - --registry-mirror=https://proxy.ai-lab.ir
        - --insecure-registry=proxy.ai-lab.ir
  before_script:
    - docker login -u "$NEXUS_USERNAME" -p "$NEXUS_PASSWORD" $NEXUS_URL
  script:
    - echo "Building image:" "$DOCKER_IMAGE"
    - docker build -f Dockerfile.Deploy -t $DOCKER_IMAGE .
    - echo "Push image:"
    - docker push $DOCKER_IMAGE
  only:
    - /^v[0-9]+(\.[0-9]+){0,2}(-rc\.[0-9]+)?$/

# --- GitOps Update Stage ---
release-candidate-gitops:
  stage: update
  trigger:
    project: platform/aip-gitops
    branch: main
    strategy: depend
  variables:
    GITOPS_CI_IMAGE_NAMESPACE: "$CI_PROJECT_NAMESPACE"
    GITOPS_CI_IMAGE_NAME: "$CI_PROJECT_NAME"
    GITOPS_CI_IMAGE_TAG: "$CI_COMMIT_TAG"
    GITOPS_CI_DOCKER_IMAGE: "$DOCKER_IMAGE"
    GITOPS_CI_TRIGGER: "true"
    GITOPS_ENVIRONMENT: "edge"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(?:\.[0-9]+)+-rc\.[0-9]+$/'

production-gitops:
  stage: update
  trigger:
    project: platform/aip-gitops
    branch: main
    strategy: depend
  variables:
    GITOPS_CI_IMAGE_NAMESPACE: "$CI_PROJECT_NAMESPACE"
    GITOPS_CI_IMAGE_NAME: "$CI_PROJECT_NAME"
    GITOPS_CI_IMAGE_TAG: "$CI_COMMIT_TAG"
    GITOPS_CI_DOCKER_IMAGE: "$DOCKER_IMAGE"
    GITOPS_CI_TRIGGER: "true"
    GITOPS_ENVIRONMENT: "edge"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+){0,2}$/'
