default:
  image: proxy.ai-lab.ir/docker:25.0
  services:
    - name: docker:dind
      alias: docker
      command:
        - --tls=false
        - --registry-mirror=https://proxy.ai-lab.ir
        - --insecure-registry=proxy.ai-lab.ir
  before_script:
variables:
  DOCKER_IMAGE: $NEXUS_URL/kong/$CI_PROJECT_NAME:$CI_COMMIT_TAG




stages:
  - build
  - update

build-image:
  stage: build
  before_script:
    # - echo "192.168.244.150 proxy.ai-lab.ir" >> /etc/hosts
    - docker login -u "$NEXUS_USERNAME" -p "$NEXUS_PASSWORD" $NEXUS_URL
  script:
    - echo "Building image:" "$DOCKER_IMAGE"
    - docker build -f Dockerfile.Deploy -t $DOCKER_IMAGE .
    - echo "Push image:"
    - docker push $DOCKER_IMAGE
  only:
    - /^v[0-9]+(\.[0-9]+){0,2}(-rc\.[0-9]+)?$/

release-candidate-gitops:
  stage: update
  variables:
    GITOPS_CI_IMAGE_NAMESPACE: $CI_PROJECT_NAMESPACE
    GITOPS_CI_IMAGE_NAME: $CI_PROJECT_NAME
    GITOPS_CI_IMAGE_TAG: $CI_COMMIT_TAG
    GITOPS_CI_TRIGGER: 'true'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(?:\.[0-9]+)+-rc\.[0-9]+$/'
  trigger:
    project: platform/aip-gitops
    branch: main

production-gitops:
  stage: update
  variables:
    GITOPS_CI_IMAGE_NAMESPACE: '$CI_PROJECT_NAMESPACE'
    GITOPS_CI_IMAGE_NAME: '$CI_PROJECT_NAME'
    GITOPS_CI_IMAGE_TAG: '$CI_COMMIT_TAG'
    GITOPS_CI_TRIGGER: 'true'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+){0,2}$/'
  trigger:
    project: platform/aip-gitops
    branch: main
