services:
  kong-db:
    image: postgres:9.6
    container_name: kong-db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kongpass
    volumes:
      - kong-data:/var/lib/postgresql/data
    networks:
      - kong-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:3.9
    container_name: kong-migrations
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
    depends_on:
      kong-db:
        condition: service_healthy
    networks:
      - kong-network

  kong:
    image: kong:3.9
    container_name: kong
    restart: unless-stopped
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8007:8000"  # Proxy (using available port)
      - "8447:8443"  # Proxy SSL (using available port)
      - "8008:8001"  # Admin API (using available port)
      - "8448:8444"  # Admin SSL (using available port)
    depends_on:
      - kong-migration
      - kong-db
    networks:
      - kong-network

  konga:
    image: pantsel/konga:latest
    platform: linux/amd64
    container_name: konga
    restart: unless-stopped
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-db
      - DB_PORT=5432
      - DB_USER=kong
      - DB_PASSWORD=kongpass
      - DB_DATABASE=kong
      - NODE_ENV=development
    ports:
      - "1338:1337"  # Konga (using available port)
    depends_on:
      - kong
      - kong-db
    networks:
      - kong-network

  # Kong Auth Service
  kong-auth:
    build: .
    container_name: kong-auth
    ports:
      - "9002:8000"
    environment:
      - HOST=0.0.0.0
      - RELOAD=true
      - KONG_ADMIN_URL=http://kong:8001
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - ENVIRONMENT=development
    volumes:
      - .:/app
    depends_on:
      - kong
    networks:
      - kong-network
    restart: unless-stopped

volumes:
  kong-data:

networks:
  kong-network:
    driver: bridge 