services:
  kong-auth:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - RELOAD=false
    depends_on:
      - kong
    networks:
      - kong-network
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  kong-network:
    external: true 